Mobile version for cricket conference page
bhushan354/capstone-conferencePage pull request #1
Opened 2023-07-31 17:00 UTC by bhushan354

2023-08-02 21:55 UTC, rica213 reviewed
# 🔴 Invalid Submission ❌

Hi Bhushan,
Nice to see you again 🥰

#### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

#### Your Code Review Request is marked as invalid for this reason:

- [ ] You do not have a professional README file. Kindly provide one, you can use the template provided by Microverse 🙏🏽 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2023-08-03 05:23 UTC, bhushan354 commented
Hello Sir/Mam , I have added proper README.md as suggested 
- also reconfigured the buttons that were not working in previous submission 
- also made sure that there should not be any kind of vertical scrolling at any device with.

Thank you ,
Bhushan .

2023-08-03 07:06 UTC, abdulhamiid requested changes
Hi @bhushan354 👋, 

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-08-03 07:06 UTC, abdulhamiid commented on README.md
> +I would like to thank Microverse and my peers for providing enough knowledge for this project
According to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md), In the Acknowledgement section, kindly give appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015).

As required by the [Creative Commons License](https://creativecommons.org/licenses/). 👍

2023-08-03 07:06 UTC, abdulhamiid commented on README.md
> +Live-Demo will be added soon.
Please, kindly add a link to the deployed version of your project under the `LIve Demo` in the README 😀👍

2023-08-03 07:06 UTC, abdulhamiid commented on index.html
> +    </header>
Template
![tempsnip](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/816a61a4-42f6-4a3f-90e7-ca497302bc29)

Your design
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/492eaccf-ec0e-449c-b91c-ef952ea232a9)

- [ ] Please let's ensure the pages should look almost identical to the original design 👍🤗

- [ ] kindly adjust your page elements to have similar `spacing`, `fonts`, `borders`, shadows, and paddings to the original design. 

- [ ] Let's use the exact same colors, for text, backgrounds, borders, etc, from the original design.

- [ ] For a good UX design, let the logo contain a hyperlink to the homepage. 🤓👍

Your design
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/2f47d16b-17ab-4d40-9951-1bf5e18642f7)

![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/1f8cf9a2-228c-4476-9171-33b1b5b18755)

Template
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/6301f00d-9e3f-4d7e-bc7a-767d8cee5069)

![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/7770beee-cb0c-4c16-aab1-de4020549fd1)

**Basic color swatch: #272A31, #EC5242, #D3D3D3**

2023-08-03 07:06 UTC, abdulhamiid commented on index.html
> +      </div>
According to the given design, the footer contains a logo aligned to the left and text aligned to the right. 👀

Template
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/b94f230a-d8b6-4cc0-9491-9e35910a80f1)

Your design
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/8c71def9-a9dc-4680-a488-fc70c09cd422)

Please adjust that 😊👍


###### Desktop Size

1. About Page: It has a dark background.

Template
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/dd9c6276-10e4-4ade-8fad-0ccb7b50e004)

Your design (About page)
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/bd953c5a-d010-4b3c-94d5-2e828e24655f)

2023-08-03 07:06 UTC, abdulhamiid commented on index.html
> +      </div>
Your design
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/d415ef5a-a498-4e40-8e9c-7d1635a9c7fd)

Template
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/2bc9c0c6-19da-4ddb-b805-f23f0a011d9d)

According to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md)
1. The pages should look almost identical to the original design, outside the content differences.
1. The pages use the exact same colors, for text, backgrounds, borders, etc, from the original design.

Please kindly change the color to match the given template 🤗👍

2023-08-03 07:06 UTC, abdulhamiid commented on index.html
> +        </p>
Template
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/622e8ba8-4713-487c-a6cc-088c1aaaf3a8)

Your design
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/902cc7aa-63b3-4eea-8ec5-9fa22945438f)

Please ensure all page elements have similar `spacing`, `borders`,  and `paddings` to the original design. 🤓

2023-08-03 07:06 UTC, abdulhamiid commented on index.html
> +        </div>
Original design
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/66e15fa4-78d2-4081-b900-987f5c8b2f4e)


Your design
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/8b8bb206-0b07-41ec-bbd4-e70f67cae8cd)

- [ ] Please adjust your design spacing `padding/margin` to match the original design
- [ ] Kindly reduce the length of the line below `Main Program` similar to the original design 👍

2023-08-03 07:06 UTC, abdulhamiid commented on app.js
> +        </div>
Original design
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/3554e15b-8d24-4782-bff0-f5a991464b7c)

Your design
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/0dba1226-3b0b-4919-b3a1-0713c7976a6c)

- [ ] Please adjust your design spacing padding/margin to match the original design
- [ ] Kindly reduce the length of the line indicated above similar to the original design 👍
- [ ] It would be nice if we increase the font size of the tiny text to enhance readability 😊
- [ ] Kindly add more space between elements  `top/bottom`.

###### Mobile
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/caf81d4c-f62d-4ad8-8dad-1b3459f6ab39)

Original design
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/6952dcd5-e607-468d-ad7d-fa4ff2d0a396)

2023-08-03 07:06 UTC, abdulhamiid commented on app.js
> +<button class="seeLess" style="display: none;">Less △</button>`;
Original desing
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/256d909d-e26d-42ca-af5a-24075744ede8)

Your design
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/4a3fb3c9-ea5e-493b-a549-c44f07110503)


- Please kindly adjust the Layout: composition and `space` between elements similar to the original design).
-Let's modify the `Button` styling to look almost identical to the original design

2023-08-03 07:06 UTC, abdulhamiid commented on index.html
> +      </div>
Your design 
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/4fa0759a-0910-4f83-b56b-aa40249b5d9d)

Original design
![image](https://github.com/bhushan354/capstone-conferencePage/assets/78251927/9883f069-c8e7-451b-82b1-ddb2a9e0cd72)

Please let' ensure the elements have similar spacing, `margins nd paddings similar to the original design. 👍

2023-08-03 13:08 UTC, BregornOriginal requested changes
Hi @bhushan354  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![hand-sketching-stair-slogan-one-step-closer-chalkboard-79948193](https://github.com/bhushan354/capstone-conferencePage/assets/93630700/23e938a8-d92d-4748-a909-2bc20b09491f)

## Highlights

✅ Linters are passing
✅ Good commit history
✅ Good work implementing some of the changes requested by the previous reviewer

***I would like to congratulate you for the great effort that are you making on this project, it's really good how it looks. But to make an impression on future recruiters in your job search, it's mandatory to follow the requirements and make it better if you can. Trust me, you will see the result at the end of the program!*** 💯 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-03 13:08 UTC, BregornOriginal commented on index.html
> +      </nav>
- [ ] Kindly as was requested by the previous reviewer. Add spacing between the social icons and webpage options to match with the design provided

Your design

![image](https://github.com/bhushan354/capstone-conferencePage/assets/93630700/58637756-b4f3-47b9-9358-be60b181850c)

Behance design

![image](https://github.com/bhushan354/capstone-conferencePage/assets/93630700/08bffef9-9ffa-4e5d-be97-fa887d903ef7)

- [ ] Kindly add a link `href` to your home page in the logo icon

![image](https://github.com/bhushan354/capstone-conferencePage/assets/93630700/4adbb98c-4210-4076-a03b-60e84f85f0f2)

2023-08-03 13:08 UTC, BregornOriginal commented on index.html
> +            <button class="campaignButton">CF Campaign</button>
- [ ] To match with the design provided, kindly modify the size of the borders and the font at your CF Campaign link. It has to be almost exact, please review the distance between elements.

Your design 

![image](https://github.com/bhushan354/capstone-conferencePage/assets/93630700/4b85013b-f2a5-491e-acc7-d7976dec4ce7)

Behance design

![image](https://github.com/bhushan354/capstone-conferencePage/assets/93630700/c291d15c-55c3-4b88-8b8a-071c9eb574a2)

2023-08-03 13:08 UTC, BregornOriginal commented on index.html
> +          <h3>2015 Cricket Fusion India<br />© All rights reserved. Unauthorized distribution prohibited. Terms apply.</h3>
- [ ] Kindly as was requested by the previous reviewer, add the space between elements in your rights reserved section at your footer. To do this you could use `flexbox` and then use the best option, as can be `space-between` 🥇 

![image](https://github.com/bhushan354/capstone-conferencePage/assets/93630700/c8e72168-fe52-4542-b69f-474af407d8c5)

2023-08-03 13:08 UTC, BregornOriginal commented on index.html
> +      <h2>Featured Speakers</h2>
Excellent work implementing some changes in your style! 💯 

As was requested by the previous reviewer there are some changes missing in this section.

- [ ] It would be great to add more `row-gap` to your different cards in the feature speakers section. Remember that it's good practice to see the different elements with the correct spacing between them and not so stretch, it looks better for the user experience. And it's like the design provided! 🥇 

Your design

![image](https://github.com/bhushan354/capstone-conferencePage/assets/93630700/07b1ddc0-4091-4798-b001-1608a61e1098)

Behance design

![image](https://github.com/bhushan354/capstone-conferencePage/assets/93630700/10e4e5f8-dbe8-4ec2-a8dc-ddc79676043f)

2023-08-03 13:08 UTC, BregornOriginal commented on index.html
> +
Excellent work implementing the `More` and `Less` functionality on this button! 💯 Kudos for this! 💯 💯 💯 

- [ ] Let's make some changes here to make your projects look exactly as the design provided. Kindly look at the bottom, it doesn't have a background color. It only has a border, the arrow it's color red, all the letters are in uppercase and the size it's smaller on the Behance design. Also, the size of the button it's almost the entry width of the screen. Please made these changes 💪🏼 

Your design

![image](https://github.com/bhushan354/capstone-conferencePage/assets/93630700/50b1d198-230f-4352-990a-0d4e63f2ce48)

Behance design

![image](https://github.com/bhushan354/capstone-conferencePage/assets/93630700/d7f85238-4e43-4187-96b8-76180bc8b5ac)

2023-08-03 14:53 UTC, bhushan354 commented
Hello sir/mam , Thank you for reviewing my code I have implemented all changes suggested by previous reviwer .

but still if something is remaining it would be of great help to me if you contact me on whatsapp or slack because after this I have to record a presentation of this project .

Thank you for consideration ,
Bhushan .

2023-08-03 15:40 UTC, Ibizugbe requested changes
Hi @bhushan354 👋🏼👋🏼👋🏼, 

![require_changes](https://github.com/bhushan354/capstone-conferencePage/assets/64643995/e81df308-bab4-4992-bb78-26e7bb6c056a)


Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights✅✅✅

- [x] Linters are passing👍🏼.
- [x] Nice job implementing some of the changes requested by the previous reviewer👍🏼.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-03 15:40 UTC, Ibizugbe commented on index.html
> +            <button class="campaignButton">CF Campaign</button>
Nice job so far👍🏼. Just as requested by the previous reviewers, Kindly do well to adjust the font colors, border color, and background to match the design as this is a requirement in this milestone👍🏼.

The image below contains the color that is specified for the design, so you can get the right color there😉. Use that color for the text and the border.

<img width="361" alt="image" src="https://github.com/bhushan354/capstone-conferencePage/assets/64643995/ea514370-1aa6-47ec-81ba-214c76584784">

yours
<img width="165" alt="image" src="https://github.com/bhushan354/capstone-conferencePage/assets/64643995/1b609696-4c48-47da-9ea6-fd50ef6a0bf1">

design
<img width="165" alt="image" src="https://github.com/bhushan354/capstone-conferencePage/assets/64643995/49e60d6e-baac-45b0-bf93-e1bfae442086">



kindly do well to also implement the right spacings between each elements as show in the image below.
<img width="455" alt="Screenshot 2023-08-03 at 16 34 28" src="https://github.com/bhushan354/capstone-conferencePage/assets/64643995/4ac90275-97f3-492c-b453-5e251c5e6b0f">

2023-08-03 16:40 UTC, christianbiring1 approved these changes
Hi @bhushan354 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 

## Highlights
- [ ] Great work on implementing the changes as suggested by the previous reviewer :+1: 
## Optional suggestions
- [ ] Kindly, you may consider adjusting the positioning of your elements to make your page more similar to the original template in your free_ time.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-03 22:13 UTC, merged